[tool.poetry]
name = "space-invaders-pygame"
version = "0.1.0"
description = ""
authors = ["svv8856 <smorudov88@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pygame = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
